#!/usr/bin/env python3
"""Seed the QA-05 golden document set into the running stack via the API.

Uploads the 10 reference documents expected by precision_at_3.py (generated by
tests/fixtures/generate.py) and waits until every one reports status=indexed.

Run (backend up, fixtures generated):
    uv run --with reportlab --with python-docx python tests/fixtures/generate.py
    HOST=http://localhost:8000 python tests/quality/seed.py

ponytail: no dedup — re-running re-uploads the same file_names, duplicating ES
chunks (same file_name, harmless for precision). Wipe the index/volume to reset.
"""

from __future__ import annotations

import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

HOST = os.environ.get("HOST", "http://localhost:8000").rstrip("/")
USER = os.environ.get("DEMO_USER", "demo")
PASSWORD = os.environ.get("DEMO_PASSWORD", "demo12345")
FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"

# The golden files, with the content-type each upload must declare.
GOLDEN = [
    ("ok.pdf", "application/pdf"),
    ("ok.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    ("ml-lecture.pdf", "application/pdf"),
    ("schedule.pdf", "application/pdf"),
    ("thesis-guide.pdf", "application/pdf"),
    ("library.pdf", "application/pdf"),
    ("scholarship.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    (
        "registration.docx",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ),
]

DOCX_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

# QA-05 distractors: share vocabulary with a golden query but are not its answer,
# so Precision@3 is measured under real ambiguity (see tests/fixtures/generate.py).
DISTRACTORS = [
    ("deep-learning-seminar.pdf", "application/pdf"),
    ("timetable.pdf", "application/pdf"),
    ("dissertation-defense.pdf", "application/pdf"),
    ("campus-hours.pdf", "application/pdf"),
    ("financial-aid-faq.docx", DOCX_TYPE),
    ("enrollment-guide.docx", DOCX_TYPE),
]

CORPUS = GOLDEN + DISTRACTORS


def login() -> str:
    body = json.dumps({"username": USER, "password": PASSWORD}).encode()
    req = urllib.request.Request(
        f"{HOST}/api/v1/auth/login", data=body, headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(req, timeout=10) as resp:  # noqa: S310 (trusted local host)
        return json.load(resp)["access_token"]


def _multipart(field: str, filename: str, content: bytes, content_type: str) -> tuple[bytes, str]:
    boundary = "----qa05seedboundary"
    body = b"".join(
        [
            f"--{boundary}\r\n".encode(),
            f'Content-Disposition: form-data; name="{field}"; filename="{filename}"\r\n'.encode(),
            f"Content-Type: {content_type}\r\n\r\n".encode(),
            content,
            f"\r\n--{boundary}--\r\n".encode(),
        ]
    )
    return body, f"multipart/form-data; boundary={boundary}"


def upload(token: str, filename: str, content_type: str) -> None:
    content = (FIXTURES / filename).read_bytes()
    body, ct = _multipart("file", filename, content, content_type)
    req = urllib.request.Request(
        f"{HOST}/api/v1/documents/upload",
        data=body,
        headers={"Content-Type": ct, "Authorization": f"Bearer {token}"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:  # noqa: S310
        doc = json.load(resp)
    print(f"  uploaded {filename} -> {doc['id']} ({doc['status']})")


def count_indexed() -> int:
    with urllib.request.urlopen(f"{HOST}/api/v1/documents", timeout=10) as resp:  # noqa: S310
        docs = json.load(resp)
    return sum(1 for d in docs if d["status"] == "indexed")


def main() -> int:
    missing = [f for f, _ in CORPUS if not (FIXTURES / f).exists()]
    if missing:
        print(
            f"missing fixtures: {missing}\nRun tests/fixtures/generate.py first.", file=sys.stderr
        )
        return 1

    token = login()
    print(
        f"== uploading {len(CORPUS)} docs "
        f"({len(GOLDEN)} golden + {len(DISTRACTORS)} distractors) to {HOST} =="
    )
    for filename, content_type in CORPUS:
        upload(token, filename, content_type)

    print("== waiting for indexing ==")
    for _ in range(60):
        indexed = count_indexed()
        print(f"  indexed {indexed}/{len(CORPUS)}")
        if indexed >= len(CORPUS):
            print("corpus indexed.")
            return 0
        time.sleep(2)
    print("indexing timed out", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
